{
 "title": "Renogy Solar",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Now", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Battery Charge",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "renogy_battery_capacity", "legendFormat": "Battery Charge" }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(renogy_battery_voltage[$__interval])",
     "legendFormat": "Solar Volts"
    }
   ]
  },
  {
   "title": "Load Voltage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(renogy_load_voltage[$__interval])",
     "legendFormat": "Solar Volts"
    }
   ]
  },
  {
   "title": "Solar Power",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(renogy_solar_power[$__interval])",
     "legendFormat": "Solar Watts"
    }
   ]
  },
  {
   "title": "Solar Voltage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(renogy_solar_voltage[$__interval])",
     "legendFormat": "Solar Volts"
    }
   ]
  },
  {
   "title": "Charging State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(renogy_charge_state[$__interval])",
     "legendFormat": "Charge State"
    }
   ]
  },
  {
   "title": "Battery Charge Current",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(renogy_battery_charge_current[$__interval])",
     "legendFormat": "Solar Current"
    }
   ]
  },
  {
   "title": "Load Current",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(renogy_load_current[$__interval])",
     "legendFormat": "Solar Volts"
    }
   ]
  },
  {
   "title": "Load Power",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(renogy_load_power[$__interval])",
     "legendFormat": "Solar Watts"
    }
   ]
  },
  {
   "title": "Solar Current",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(renogy_solar_current[$__interval])",
     "legendFormat": "Solar Current"
    }
   ]
  },
  { "title": "Today", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Battery Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "renogy_today_battery_voltage_max",
     "legendFormat": "Max"
    },
    {
     "expr": "renogy_today_battery_voltage_min",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Battery Max Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "renogy_today_battery_charge_current_max",
     "legendFormat": "Charge"
    },
    {
     "expr": "renogy_today_battery_discharge_current_max",
     "legendFormat": "Discharge"
    }
   ]
  },
  {
   "title": "Battery Max Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "renogy_today_battery_charge_power_max",
     "legendFormat": "Charge"
    },
    {
     "expr": "renogy_today_battery_discharge_power_max",
     "legendFormat": "Discharge"
    }
   ]
  },
  {
   "title": "Charging",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "amph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "renogy_today_charge_ah", "legendFormat": "In" },
    { "expr": "renogy_today_discharge_ah", "legendFormat": "Out" }
   ]
  },
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Power Generation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(renogy_total_power_generated[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(renogy_total_power_consumed[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Charge",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "amph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(renogy_total_charge_ah[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discharge",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "amph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(renogy_total_discharge_ah[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Battery Charge %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "renogy_battery_capacity", "legendFormat": "Battery level" },
    { "target": [ "sun_altitude" ] }
   ]
  },
  {
   "title": "Solar Volts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "renogy_solar_voltage", "legendFormat": "Volts" }
   ]
  },
  {
   "title": "Solar Power (In)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "renogy_solar_power", "legendFormat": "Watts" },
    { "target": [ "sun_altitude" ] }
   ]
  },
  {
   "title": "Solar Current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "renogy_solar_current", "legendFormat": "Amps" }
   ]
  },
  {
   "title": "Load Volts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "renogy_load_voltage", "legendFormat": "Volts" }
   ]
  },
  {
   "title": "Load Power (Out)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "renogy_load_power", "legendFormat": "Load Watts" }
   ]
  },
  {
   "title": "Load Current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "renogy_load_current", "legendFormat": "Amps" }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "renogy_battery_voltage", "legendFormat": "Volts" }
   ]
  },
  {
   "title": "Battery Charge Current",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "renogy_battery_charge_current", "legendFormat": "Amps" }
   ]
  },
  {
   "title": "Battery Temperature (F)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "farenheit" } },
   "targets": [
    { "expr": "renogy_battery_temp * 1.8 + 32", "legendFormat": "Temperature" }
   ]
  },
  {
   "title": "Controller Temperature (F)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "renogy_controller_temp * 1.8 + 32",
     "legendFormat": "Temperature"
    },
    { "target": [ "sun_altitude" ] }
   ]
  },
  {
   "title": "Host CPU Temperature (F)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "renogy_host_cpu_temp * 1.8 + 32",
     "legendFormat": "Temperature"
    },
    { "target": [ "sun_altitude" ] }
   ]
  }
 ]
}